#!/usr/bin/env python3
import os
import sys
import json
import yaml
import argparse
from pathlib import Path
from datetime import datetime

# Paths relative to this script
REPO_ROOT = Path(__file__).parent.parent.resolve()
DOCS_DIR = REPO_ROOT / "docs"
CATALOG_MD_PATH = DOCS_DIR / "catalog.md"
CATALOG_JSON_PATH = DOCS_DIR / "catalog.json"

# Directories to exclude during recursive search
EXCLUDE_DIRS = {
    "templates",
    ".venv",
    "venv",
    "__pycache__",
    ".git",
    ".github",
    ".archive",
    ".janitor",
    ".pytest_cache",
    "node_modules",
}

STATUS_EMOJIS = {
    # Modules
    "implemented": "🟢 `implemented`",
    "active": "🟢 `active`",
    "stable": "🟢 `stable`",
    "mock": "🟡 `mock`",
    "scaffold": "⚪ `scaffold`",
    "future": "🔴 `future`",
    "external": "🔵 `external`",
    # Solutions
    "partial": "🟡 `partial`",
    "executable": "🟢 `executable`",
}

def parse_yaml_file(path: Path) -> dict:
    """Parses a YAML file and returns its content as a dictionary."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            content = yaml.safe_load(f)
            if not isinstance(content, dict):
                return {}
            return content
    except Exception as e:
        print(f"Warning: Failed to parse YAML at {path}: {e}", file=sys.stderr)
        return {}

def should_exclude(path: Path) -> bool:
    """Checks if a path should be excluded based on EXCLUDE_DIRS."""
    parts = path.parts
    return any(exclude in parts for exclude in EXCLUDE_DIRS)

def scan_building_blocks() -> list:
    """Scans all building blocks in the repository."""
    blocks = []
    bb_root = REPO_ROOT / "building-blocks"
    if not bb_root.exists():
        return blocks

    for yaml_path in bb_root.glob("**/module.yaml"):
        if should_exclude(yaml_path):
            continue

        relative_dir = yaml_path.parent.relative_to(REPO_ROOT).as_posix()
        meta = parse_yaml_file(yaml_path)
        if not meta:
            continue

        name = meta.get("name", yaml_path.parent.name)
        category = meta.get("category", yaml_path.parent.parent.name)
        status = meta.get("status", "scaffold")
        purpose = meta.get("purpose", "")
        azure_resources = meta.get("azure_resources", [])
        inputs = meta.get("inputs", [])
        outputs = meta.get("outputs", [])

        blocks.append({
            "name": name,
            "category": category,
            "path": relative_dir,
            "status": status,
            "purpose": purpose,
            "azure_resources": azure_resources,
            "inputs": inputs,
            "outputs": outputs
        })

    # Sort by category then by name
    return sorted(blocks, key=lambda x: (x["category"], x["name"]))

def scan_solutions() -> list:
    """Scans all solutions in the repository."""
    solutions = []
    solutions_root = REPO_ROOT / "solutions"
    if not solutions_root.exists():
        return solutions

    for yaml_path in solutions_root.glob("**/solution.yaml"):
        if should_exclude(yaml_path):
            continue

        relative_dir = yaml_path.parent.relative_to(REPO_ROOT).as_posix()
        meta = parse_yaml_file(yaml_path)
        if not meta:
            continue

        name = meta.get("name", yaml_path.parent.name)
        status = meta.get("status", "scaffold")
        purpose = meta.get("purpose", "")
        building_blocks = meta.get("building_blocks", [])
        inputs = meta.get("inputs", [])
        outputs = meta.get("outputs", [])

        solutions.append({
            "name": name,
            "path": relative_dir,
            "status": status,
            "purpose": purpose,
            "building_blocks": building_blocks,
            "inputs": inputs,
            "outputs": outputs
        })

    # Sort by name
    return sorted(solutions, key=lambda x: x["name"])

def format_status(status: str) -> str:
    """Formats the status string with an emoji indicator."""
    return STATUS_EMOJIS.get(status.lower(), f"`{status}`")

def format_list(items: list) -> str:
    """Formats a list of strings cleanly for markdown."""
    if not items:
        return "-"
    return ", ".join(f"`{item}`" if isinstance(item, str) else f"`{item.get('name', '')}`" for item in items)

def generate_markdown(blocks: list, solutions: list) -> str:
    """Generates the human-readable catalog markdown."""
    md = []
    md.append("# Azure Reference Kit Catalog")
    md.append("")
    md.append("This catalog is auto-generated from module and solution metadata. Do not edit this file directly.")
    md.append("")
    md.append(f"*Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
    md.append("")
    md.append("---")
    md.append("")

    # Solutions Section
    md.append("## 🚀 Composed Solutions")
    md.append("")
    md.append("Solutions compose multiple building blocks into functional, end-to-end customer architectures.")
    md.append("")
    md.append("| Solution | Status | Description | Inputs | Outputs |")
    md.append("| :--- | :--- | :--- | :--- | :--- |")
    for sol in solutions:
        link = f"../{sol['path']}"
        name_cell = f"[{sol['name']}]({link})"
        status_cell = format_status(sol["status"])
        purpose_cell = sol["purpose"].replace("\n", " ")
        inputs_cell = format_list(sol["inputs"])
        outputs_cell = format_list(sol["outputs"])
        md.append(f"| {name_cell} | {status_cell} | {purpose_cell} | {inputs_cell} | {outputs_cell} |")

    md.append("")
    md.append("---")
    md.append("")

    # Building Blocks Section
    md.append("## 📦 Reusable Building Blocks")
    md.append("")
    md.append("Building blocks are modular, self-contained components that implement single responsibilities.")
    md.append("")
    md.append("| Module | Category | Status | Description | Azure Resources | Inputs | Outputs |")
    md.append("| :--- | :--- | :--- | :--- | :--- | :--- | :--- |")
    for block in blocks:
        link = f"../{block['path']}"
        name_cell = f"[{block['name']}]({link})"
        category_cell = f"`{block['category']}`"
        status_cell = format_status(block["status"])
        purpose_cell = block["purpose"].replace("\n", " ")
        resources_cell = format_list(block["azure_resources"])
        inputs_cell = format_list(block["inputs"])
        outputs_cell = format_list(block["outputs"])
        md.append(f"| {name_cell} | {category_cell} | {status_cell} | {purpose_cell} | {resources_cell} | {inputs_cell} | {outputs_cell} |")

    md.append("")
    return "\n".join(md)

def main():
    parser = argparse.ArgumentParser(description="Generate and validate the solutions/modules catalog.")
    parser.add_argument("--check", action="store_true", help="Validate that the catalog files are up-to-date without writing changes.")
    args = parser.parse_args()

    # Ensure docs directory exists
    DOCS_DIR.mkdir(parents=True, exist_ok=True)

    # Scan directories
    blocks = scan_building_blocks()
    solutions = scan_solutions()

    # Generate payloads
    new_json_content = json.dumps({
        "last_updated": datetime.now().isoformat(),
        "building_blocks": blocks,
        "solutions": solutions
    }, indent=2)

    new_md_content = generate_markdown(blocks, solutions)

    # Check mode
    if args.check:
        mismatch = False

        # Check JSON
        if CATALOG_JSON_PATH.exists():
            try:
                with open(CATALOG_JSON_PATH, "r", encoding="utf-8") as f:
                    current_json = json.load(f)

                # Check structure parity (ignoring last_updated)
                new_struct = json.loads(new_json_content)
                new_struct.pop("last_updated", None)
                current_json.pop("last_updated", None)

                if new_struct != current_json:
                    print("Error: Catalog JSON is out of sync with workspace metadata.", file=sys.stderr)
                    mismatch = True
            except Exception as e:
                print(f"Error reading/parsing current catalog.json: {e}", file=sys.stderr)
                mismatch = True
        else:
            print("Error: docs/catalog.json does not exist.", file=sys.stderr)
            mismatch = True

        # Check Markdown
        if CATALOG_MD_PATH.exists():
            try:
                with open(CATALOG_MD_PATH, "r", encoding="utf-8") as f:
                    current_md = f.read()

                # Compare without the 'Last updated:' line to avoid false positives
                def strip_last_updated(content: str) -> str:
                    return "\n".join(line for line in content.splitlines() if not line.startswith("*Last updated:"))

                if strip_last_updated(new_md_content) != strip_last_updated(current_md):
                    print("Error: Catalog Markdown is out of sync with workspace metadata.", file=sys.stderr)
                    mismatch = True
            except Exception as e:
                print(f"Error reading current catalog.md: {e}", file=sys.stderr)
                mismatch = True
        else:
            print("Error: docs/catalog.md does not exist.", file=sys.stderr)
            mismatch = True

        if mismatch:
            print("\nPlease run 'python scripts/generate_catalog.py' to regenerate the catalog.", file=sys.stderr)
            sys.exit(1)

        print("Catalog validation successful. Everything is in sync.")
        sys.exit(0)

    # Write files
    try:
        with open(CATALOG_JSON_PATH, "w", encoding="utf-8") as f:
            f.write(new_json_content)
        print(f"Successfully generated {CATALOG_JSON_PATH}")

        with open(CATALOG_MD_PATH, "w", encoding="utf-8") as f:
            f.write(new_md_content)
        print(f"Successfully generated {CATALOG_MD_PATH}")

    except Exception as e:
        print(f"Error writing catalog files: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
